# Generated by Django 2.2.6 on 2019-10-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='provided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
