# Generated by Django 2.2.6 on 2019-10-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20191025_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyToSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Solution')),
            ],
        ),
    ]
