# Generated by Django 2.2.6 on 2019-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191024_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_solutions_count',
            field=models.IntegerField(default=0),
        ),
    ]
